### ISSUE TITLE
Parsing errors in read_gv100() (version = "AD")

### ISSUE THREAD

**Issue by DominikVogel** [sumtxt/wiesbaden#13]
When reading the most recent Gemeindeverzeichnis using the `read_gv100()` function I get a lot of errors:

```
Warning: 3423 parsing failures.
row   col   expected      actual                                            file
 10 bev   an integer 90000021653 XXX
 13 bev   an integer 60000008019 XXX
 13 bev_m an integer 60000003972 XXX
 29 bev   an integer 40000000003 XXX
 29 bev_m an integer 60000000001 XXX
... ..... .......... ........... ...............................................
See problems(...) for more details.
```

The errors are produced by the columns `bev` and `bev_m`. The values for `bev` and `bev_m` in the file seem to be too big for an integer. When manually changing the col_type for the two columns everything works fine. 

I would fix the error myself and make a pull request but I failed to change the col_types stored in `sysdata.rds`. In my opinion the only thing that needs to be changed are the values for `bev` and `bev_m` in `gv100[["ad"]][["col"]]` (stored in `sysdata.rds`).

**Comment by DominikVogel** [comment]
I checked again and the values for `bev` and `bev_m` are unrealistic. It seems like there is some error in the function.

**Comment by sumtxt** [comment]
Can you link to the file you are trying to load? Thx

**Comment by DominikVogel** [comment]
Sure. It is this one: https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GV100ADJ/GV100AD31122019.html;jsessionid=090C5BCAE8C01728D5FDD4F987C03DDE.live741 (GV100AD Jahresausgabe am 31.12.2019)

**Comment by DominikVogel** [comment]
In case it is relevant, this is the code I used:
```
read_gv100(file = "GV100AD_311219.txt",
   stzrt = 60,
   version = "AD",
   lcl = locale(encoding = "utf-8"))
```

**Comment by sumtxt** [comment]
It seems that their file format has changed. Reading the 2018 version of the file works just fine but 2019 fails. I don't have time to follow-up with them but if you can get more information about this change, please share.

**Comment by DominikVogel** [comment]
I will have a look. I found a frist clue. The difference between 2018 and 2019 is not the file format but the encoding. The information provided by the Statistische Bundesamt says that the encoding was changed to UTF-8 to include the Sorbic names of some cities. I found out that the code breaks when a city name includes a Umlaut (e.g., Lübeck).

**Comment by DominikVogel** [comment]
I solved it, thanks to this post: https://github.com/tidyverse/readr/issues/852.

The problem is, that column positions in fixed width files refer to bytes not characters. Special characters such as Umlauts require more bytes. The sollution is to read the file at once, change the encoding to latin-1, and parse it with latin-1 encoding. Here is a working example:

```r
x <- readr::read_lines(
  "GV100AD_311219.txt",
  locale = readr::locale(encoding = "UTF-8")
)

y <- iconv(x, from = "UTF-8", to = "latin1")

r3 <- wiesbaden::read_gv100(y,
                 stzrt = 60,
                 version = "AD",
                 lcl = locale(encoding = "latin1"))
```

**Comment by sumtxt** [comment]
OK, got it. I will incorporate a fix later today.
