### ISSUE TITLE
Available databases

### ISSUE THREAD

**Issue by olileitner** [sumtxt/wiesbaden#14]
I'm new to programming and github. Please tell me if I'm not doing this right.

Here
  https://sumtxt.github.io/wiesbaden/reference/wiesbaden-package.html
it says:

"Available databases are regionalstatistik.de (shortname: "regio"), landesdatenbank.nrw.de ("nrw"), www-genesis.destatis.de ("de") and bildungsmonitoring.de ("bm"), genesis.sachsen-anhalt.de ("st") and statistikdaten.bayern.de ("by")."

But when using
`save_credentials(user="myusername", password="mypassword", db="by")`

I get:
Error in save_credentials(user = "...", password = "...",  : 
  Database 'by' unknown.

**Comment by olileitner** [comment]
I also get:

> test_login(genesis=c(db="regio") )
Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element nicht gefunden.

although save_credentials returned: "Successfully added credentials." (for regio).

**Comment by olileitner** [comment]
My mistake: "by" is only included in the latest version from github.

**Comment by sumtxt** [comment]
I updated the documentation. Unfortunately the data API is still offline.

**Comment by maraab23** [comment]
> I updated the documentation. Unfortunately the data API is still offline.

Do you have any idea when the data for Bavaria will be accessible via the API (or whom from statistikdaten.bayern I should contact to ask) ? I am currently downloading each table manually, and automating the data retrieval would be really awesome.

**Comment by sumtxt** [comment]
I don't know but feel free to email GENESIS-ONLINE@statistik.bayern.de. I reach out to them on June 11 asking for an update on their timetable but haven't heard back from them since.

**Comment by maraab23** [comment]
Thanks for the fast response. I will write them. Maybe it reminds them that there is a demand for such *weird* things.

**Comment by stefanlinner** [comment]
I also emailed them and they told me that they decided to not be part of this R package (for whatever reason). But at the same time, they told me that the Webservice is available and sent me the link to their web service. However, when I conduct an API request (which is given as an example in their documentation file) I get a 500 HTTP status code. So just to clarify do you know if it's possible to somehow actually do API requests to genesis.bayern, as their E-Mail implied that, but I'm not able to make it work. Maybe you have some more information regarding that topic.

Thanks a lot in advance and keep up the great work with the package!

**Comment by olileitner** [comment]
I know very little about programming. But if I try this in my Browser (with correct credentials) it does generate a response with content (no error message): 

https://www.statistikdaten.bayern.de/genesisWS/web/ExportService_2010?method=TabellenExport&kennung=XXXX&passwort=XXXXX&namen=11111-001r&bereich=alle&format=csv&zeitscheiben=1&startjahr=&endjahr=&regionalmerkmal=&regionalschluessel=&sachmerkmal=&sachschluessel=&sachmerkmal2=&sachschluessel2=&sachmerkmal3=&sachschluessel3=&strukturinformation=true&komprimieren=false&transponieren=false&stand=&auftrag=false&sprache=de

helper.R seems to use "https://www.statistikdaten.bayern.de/genesis/online" instead of  "https://www.statistikdaten.bayern.de/genesisWS/services/" (see download_csv.R line 33).

**Comment by stefanlinner** [comment]
Thanks for your answer! Your example also works for me for the method=TabellenExport, where I initially run into problems was for the method=DatenExport. The method=DatenExport is also used in the wiesbaden package (see retrieve_data.R). In the official API documentation is the following example given: 

https://www-genesis.destatis.de/genesisWS/web/ExportService_2010?method=DatenExport&kennung=IH
RE_KENNUNG&passwort=IHR_PASSWORT&namen=21311BS003&bereich=Alle&format=csv&werte=true&metadaten
=false&zusatz=false&startjahr=&endjahr=&zeitscheiben=1&inhalte=&regionalmerkmal=&regionalschlu
essel=&sachmerkmal=GES&sachschluessel=GESW&sachmerkmal2=NAT&sachschluessel2=NATA&sachmerkmal3=
&sachschluessel3=&stand=01.01.1900&sprache=de 

However, if I use my credentials it doesn't work. But with your answer I at least have an alternative approach to work with :)

**Comment by olileitner** [comment]
You're right, with "DatenExport" it responds:
"genesis.webservice.util.exception.XMLGenesisException: Sie sind nicht berechtigt diesen Service aufzurufen! (KDTYP)"

Would it be an alternative to use "TabellenExport"?
I hope you find a solution.

**Comment by stefanlinner** [comment]
Yes, "TabellenExport" is definitely better than nothing, just some more formatting is necessary, but this is doable. So thank you! :)

**Comment by sumtxt** [comment]
It's unfortunate that some of the Länder offices are not enabling all GENSIS APIs. It's seems that Bavaria enabled the TabellenExport API but not the ExportService API. It's my understanding that the ExportService API provides access to more data than the TabellenExport API. It certainly returns the data in a more easy-to-process matrix-like csv without any multi-line/multi-column headers. The latter actually motivated the choice to use the ExportService API in `wiesbaden`.

**Comment by sumtxt** [comment]
It's also unfortunate that they don't engage more with the community of data users.
