### ISSUE TITLE
Error in retrieving table "33111GJ005"

### ISSUE THREAD

**Issue by fmssn** [sumtxt/wiesbaden#16]
#### Description
`data <- retrieve_data(tablename="33111GJ005", genesis=c(db='regio'))` leads to the Error `Error in if (length(res) == 0 || res == -1) { : 
  missing value where TRUE/FALSE needed`. 
Retrieving metadata from the same exact table works, the table also shows when calling e.g. `d <- retrieve_datalist(tableseries="33111*", genesis=c(db='regio')) ``.

#### Screenshots
![error](https://user-images.githubusercontent.com/52298176/189617061-01879517-6d2d-43de-b3d9-90121ba520c3.png)

#### To Reproduce
Call `data <- retrieve_data(tablename="33111GJ005", genesis=c(db='regio'))`.

**Comment by sumtxt** [comment]
Thanks for reporting. I was able to reproduce this error. Seems like the table has a peculiar format. Going to look into it.

**Comment by sumtxt** [comment]
Thanks again for reporting. As it turns out the cube 33111GJ005 is empty. This is peculiar as the cube catalog should not list an empty cube. All other cubes in the same series are available and download normally (see below). I will append the package to provide a more informative error message. 

```
# Bodenfläche, Gemeinden, Stichtag
d33111GJ001 <- retrieve_data(tablename="33111GJ001", genesis=c(db='regio'))
# Bodenfläche, Gemeinden, Nutzungsartenverzeichnis, Stichtag
d33111GJ002 <- retrieve_data(tablename="33111GJ002", genesis=c(db='regio'))
# Bodenfläche, Gemeinden, Gebäude- und Freifläche, Stichtag
d33111GJ003 <- retrieve_data(tablename="33111GJ003", genesis=c(db='regio'))
# Bodenfläche, Bodenfläche in m², Gemeinden, Stichtag
d33111GJ004 <- retrieve_data(tablename="33111GJ004", genesis=c(db='regio'))
# Bodenfläche, Gemeinden, Landwirtschaftsfläche, Stichtag
d33111GJ006 <- retrieve_data(tablename="33111GJ006", genesis=c(db='regio'))
# Bodenfläche, Gemeinden, Flächen anderer Nutzung (ohne Friedhofsfläche), Stichtag
d33111GJ007 <- retrieve_data(tablename="33111GJ007", genesis=c(db='regio'))
```

**Comment by fmssn** [comment]
Oh so this is an error in the Destatis API? Thank you for clearing this out! 

And thank you for your very valuable package, it is much appreciated!

**Comment by sumtxt** [comment]
No, the error you got is from R as the retrieve_data function tries to read the data from the DESTATIS API response XML but it doesn't include any data. I didn't anticipate that an API response could not include any data but just the header and meta data.

**Comment by fmssn** [comment]
But I mean the data is definitely there for e.g. regular xlsx files, so the API should include the respective data I guess (not only header and metadata). I would be surprised if this behaviour is intentional on their side.

**Comment by sumtxt** [comment]
Can you send a link to the file or table you have in mind? I am not seeing a table that uses "Nutzungsarten (AdV-Nutzungsartenkatalog 2009)": https://www.regionalstatistik.de/genesis/online?operation=variable&levelindex=0&levelid=1663347438565&code=ADV09A&option=table#abreadcrumb

**Comment by fmssn** [comment]
https://www.regionalstatistik.de/genesis//online?operation=table&code=33111-01-02-5&bypass=true&levelindex=0&levelid=1663348377992#abreadcrumb

I am particular looking at this one. Your package/data worked with Kreisebenen.

**Comment by sumtxt** [comment]
OK, that was helpful. The problem is the size of the data cube. It seems that the API can't handle to download the entire data cube and therefore defaults to return nothing. When you slice the cube by year, it does return the requested data:  

`d33111GJ005_2019  <- retrieve_data(tablename="33111GJ005", genesis=c(db='regio'), startyear='2019')`

**Comment by m-wiegand** [comment]
Same issue when trying to retrieve the table 12521KJ003 (or 12521KJ010). Restricting the time period to one year does not work either. 

Code: 
`retrieve_data(tablename = '12521KJ003', genesis = c(db = 'de'), startyear = '2019', endyear = '2019')`

**Comment by sumtxt** [comment]
Thanks for reporting. Seems like that the table `12521KJ003` is too big even after slicing only one year from the data cube. Requesting fewer datapoints helps: 

`retrieve_data(tablename = '12521KJ003', genesis = c(db = 'de'), startyear = '2019', endyear = '2019', regionalschluessel="01001", regionalmerkmal="KREISE")`

I will further expand the documentation to help navigating the issue. Again, thanks for reporting.
