### ISSUE TITLE
Some recommendations for the R Vignette

### ISSUE THREAD

**Issue by bathyscapher** [sumtxt/wiesbaden#17]
Hello,

thirst, thank you for this handy package :)
My message is not really an issue, it's more two recommendations to improve the R Vignette:

### Mention additional libraries
It would be helpful to mention the necessary libraries somewhere:
```
library(stringr)
library(dplyr)
```

### Specify package for `filter()`
There's also a `stats::filter()` that belongs to base R and I think it would be helpful to specify from which package this function originates (it actually took me some time to figure it out):
```
dplyr::filter(d, str_detect(description, "Kreise"))
```
Or maybe even like (so that it's clear where `stringr` is used):
```
dplyr::filter(d, stringr::str_detect(description, "Kreise"))
```

All the best,
bathyscapher

**Comment by sumtxt** [comment]
Thank you, this is very helpful. I will make some revisions to the vignette.
