### ISSUE TITLE
Connectivity Broken: "Ein Fehler ist aufgetreten. (Der Anwendungsserver ist nicht vorhanden.)"

### ISSUE THREAD

**Issue by CubicTom** [sumtxt/wiesbaden#18]
Connecting to destatis api stopped working. Username and password are connected to a premium license. Package version installed is 1.2.5, R version is 4.2.1.

```
> library(wiesbaden)
> g <- c(user = username, password = password, db = "de") 

> test_login(genesis = g)
[1] "Ein Fehler ist aufgetreten. (Der Anwendungsserver ist nicht vorhanden.)"

> retrieve_metadata(tablename = "61241BM002", genesis = g)
[1] "soapenv:Server.userExceptiongenesis.webservice.util.exception.XMLGenesisException: Ein Fehler ist aufgetreten. (Der Anwendungsserver ist nicht vorhanden.)www-genesisb"
```

This code did work in the past, but no longer does. A fix or any advice on how to fix this on the user-side would be highly appreciated.

Best wishes 
Thomas

**Comment by sumtxt** [comment]
There is a server-side issue. The API seems to be down. I expect that DESTATIS is working on this already but you might email them directly: genesis-online@destatis.de
