### ISSUE TITLE
What's the syntax to add other arguments send to httr::GET request?

### ISSUE THREAD

**Issue by bathyscapher** [sumtxt/wiesbaden#19]
I want to extract the full list of GEMEINDEN (municipialities) from Regionalstatistik. However, `retrieve_valuelabel()` delivers maximal 2500 entries (although there should be 11,007 municipialities):

```
> gemeinden <- retrieve_valuelabel("GEMEIN",
                                   genesis = c(db = 'regio'))
> dim(gemeinden)
[1] 2500    2
```
According to the manual, it's possible to add "other arguments send to the httr::GET request".
So I tried - without success though - the parameter `pagelength` that [should increase the number of items delivered](https://www-genesis.destatis.de/genesis/misc/GENESIS-Webservices_Einfuehrung.pdf):

```
> gemeinden <- retrieve_valuelabel("GEMEIN",
                                   genesis = c(db = 'regio'),
                                   pagelength = 12000)
> dim(gemeinden)
[1] 2500    2
```

Now I'm wondering what is the syntax to increase the amount of items or, more generally, to add other arguments?

Thank you!

**Comment by sumtxt** [comment]
`retrieve_valuelabel()` uses the API service MerkmalAuspraegungenKatalog. The documentation is here: https://www-genesis.destatis.de/genesis/misc/GENESIS-Webservices_Einfuehrung.pdf (page 167). It's not obvious to me how you can get more than 2.5k labels as there are no other parameters to select a subset of labels (and 2.5k is the hard retrieval limit). 

If you want to get a recent list of municipalities, you could get it via: 

m <- retrieve_data("11111GJ001", genesis=c("db"='regio'), startyear=2020, endyear=2020)

But a better way might be to download the official municipality register here (https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/_inhalt.html).

**Comment by bathyscapher** [comment]
Ah, okay, interesting. Then I wonder why
```
head(retrieve_valuelabel("GEMEIN",
                         genesis = c(db = 'regio')))
```
yields
```
    GEMEIN                  description
1 01001000  Flensburg, kreisfreie Stadt
2 01002000       Kiel, kreisfreie Stadt
3 01003000     Lübeck, kreisfreie Stadt
4 01004000 Neumünster, kreisfreie Stadt
5 01051001                   Albersdorf
6 01051002                      Arkebek
```
I interpreted this as the list of municipialities, I was looking for...

Anyway, thank you for showing me (other) solutions! :)

**Comment by sumtxt** [comment]
`retrieve_valuelabel` gets the value labels for variables returned by `retrieve_data`. Therefore, the list includes all municipality codes (names) ever used including those that are discontinued due to municipality mergers.
