### ISSUE TITLE
"No results found" in a request for a bigger table 

### ISSUE THREAD

**Issue by tosigus** [sumtxt/wiesbaden#2]
**R Code**
```
install_github("sumtxt/wiesbaden")
genesis <- c(user=" ", password=" ", db=" ")
real <- retrieve_data(tablename = "71231GJ001", genesis = genesis)  
```
 
**Results**
```
View(real) 
"No results found."
```
Using other tablenames / retreive_metadata is working:

```
real_metadaten <- retrieve_metadata(tablename="71231GJ001", genesis=genesis)
```

**Workaround** 

Download and import with read_header_genesis

**Question**

Is it a setting or timeout in the package? 

Or something in the SOAP protocol at destatis?

**Comment by sumtxt** [comment]
No, its their server: "Der Datenexport im Dialog ist auf maximal 1000000 Wertfelder beschränkt. Bitte verfeinern Sie die Auswahl, um den Export durchführen zu können." Sorry.

**Comment by tosigus** [comment]
Thanks for the quick response. 

I thought so already. Can I limit the query?

**Comment by sumtxt** [comment]
The easiest would be to use the startyear/endyear parameters. But it looks like that even the one-year slice is too large. The next best option is to go state by state, ie. 

`real <- retrieve_data(tablename = "71231GJ001", genesis = c(db="regio"), regionalschluessel="13*" )`

which gets you the data for Mecklenburg-Vorpommern.

**Comment by tosigus** [comment]
Perfect. Thanks!
