### ISSUE TITLE
translation between destatis codes and wiesbaden codes

### ISSUE THREAD

**Issue by GreenGrassBlueOcean** [sumtxt/wiesbaden#21]
Many thanks for this amazing and user friendly package.

I was wondering if there is any way to translate destatiscodes e.g. (31111-0006 Baugenehmigungen im Fertigteilbau (Neubau): Deutschland,Monate, Gebäudeart/Bauherr) 

[destatis_link](https://www-genesis.destatis.de/genesis//online?operation=table&code=31111-0006&bypass=true&levelindex=0&levelid=1683292213773#abreadcrumb
)

into the wiesbaden codes like 31111 [{LJ},{BM},{BJ}] [ {001-003}].

I looked up the code using:
`tables <- retrieve_datalist( tableseries="3*"
                                          , genesis = c(db = "de", user = "fake_user", password = "fake_pass")
                                          , language = "de")`

I was however not able to find in the description the word Baugenehmigungen.
Is this because it is the title of the table (and ifso is it also possible to print also the title of table?) and that description actually stands for the displayed variables in the table?

**Comment by sumtxt** [comment]
Translations are provided by the API and not the package. For questions about the tables and the data, please contact DESTATIS.
