### ISSUE TITLE
Fehler beim Download

### ISSUE THREAD

**Issue by Lit-Fam** [sumtxt/wiesbaden#22]
Heute kann ich keine Daten mit Wiesbaden herunterladen. Wenn ich versuche, eine Tabelle herunterzuladen, erhalte ich anstelle meiner Tabelle diese Fehlermeldung: 
soapenv:Server.userExceptiongenesis.webservice.util.exception.XMLGenesisException: Ein Fehler ist aufgetreten. (Bitte prüfen und korrigieren Sie Ihren Nutzernamen bzw.\n das Passwort.)idmz-pin1-12107.m00.idmz.nrw.de

Ich habe meinen Benutzernamen und mein Passwort überprüft, sie funktionieren immer noch, wenn ich sie in [genesis](https://www.regionalstatistik.de/genesis/online?Menu=Anmeldung) verwende.

Das von mir verwendete Skript hat am 13.03.2023 funktioniert.

PS: ich bin großer Fan von diesem Package, es hat mein Leben sowas von erleichtert.

**Comment by sumtxt** [comment]
Can you pls post an example? What's the output of test_login()?

**Comment by Lit-Fam** [comment]
Kudos for the speedy reply. It turns out changing my Regionaldatenbank password did the trick. In all likelihood, a special character in my password and some encoding setting burried somewhere in the depths of RStudio were conspiring against me. Sorry for the trouble and thank you for this awesome repository!

**Comment by sumtxt** [comment]
Thank you! Could you share one of the special characters you had used in the password? This is second time this came up and it seems that there might be an encoding issue in the package backend.

**Comment by Lit-Fam** [comment]
The characters my previous password were as follows:
.?abefJKorsTV

Changing back to the previous password doesn't allow me to reproduce the problem with the old R script. I have no idea what the problem was, but changing the password seems to have permanently solved it.
