### ISSUE TITLE
Add RESTful/JSON support for Census Database

### ISSUE THREAD

**Issue by mirkoj** [sumtxt/wiesbaden#23]
Dear sumtxt,

thanks for your handy package! I was wondering whether it would be possible to add support for the RESTful/JSON Interface of API Version 4.3. This would allow the integration of the cencus database webservice (https://ergebnisse2011.zensus2022.de/datenbank/misc/ZENSUS-Webservices_Einfuehrung.pdf). 

Best Regards

**Comment by sumtxt** [comment]
I am happy to support rewriting the backend but I currently have no capacity to do it on my own.

**Comment by mirkoj** [comment]
Please see my fork for a first suggestion (branch Issue23). I introduced a new parameter "restapi" which is false by default. If true, the set_api function uses the proper url and the corresponding data function handles the incoming json data to generate the common result. So far, this seems to work for test_login, retrieve_datalist and retrieve_data (tested with table 12411BJ005). The retrieve_datalist offers a bit more information about the data sources and the name of the first column contains the appendix "_rest" to check whether the right process flow is used.

**Comment by sumtxt** [comment]
Thank you. Feel free to submit your code via a pull request and I take a look.

**Comment by sumtxt** [comment]
I am parking this work for now as there is a new package that links up to the REST API (https://cran.r-project.org/web/packages/restatis/index.html). It might be easier to link up to https://ergebnisse2011.zensus2022.de/ using this package.
