### ISSUE TITLE
Question: Table name on website vs API Name

### ISSUE THREAD

**Issue by skriptum** [sumtxt/wiesbaden#27]
First of all thanks for the great package. 

I have a question regarding the table names. When I search for data on the regionalstatistik website, I see the tables names like [13211-02-05-4](https://www.regionalstatistik.de/genesis//online?operation=table&code=13211-02-05-4&bypass=true&levelindex=0&levelid=1704889912125#abreadcrumb). 

But to access this table, i cant just paste this name into the function in wiesbaden. Is there a way of finding out the name of the table on the website or o i always have to search the data cubes in the api for it? 

Thanks for the help

**Comment by sumtxt** [comment]
I am not aware of any easy mapping between the table IDs and the cube IDs. My observation is that the the first two digits are typically identical.
