### ISSUE TITLE
Breaking Change ahead: Destatis will discontinue SOAP web service and switch from GET to POST

### ISSUE THREAD

**Issue by CubicTom** [sumtxt/wiesbaden#28]
Dear Moritz,

today Destatis announced the release of a new user interface of GENESIS-Online. The announcement can be found here: https://www-genesis.destatis.de/datenbank/beta/announcement

Importantly, it includes an announcement concerning the api: 

> Geplante Änderungen an den API-Schnittstellen in 2025:
> 
> - Abschaltung der SOAP-Schnittstelle
> - Umstieg von GET- auf POST-Requests
> Konkrete Informationen dazu werden frühzeitig an dieser Stelle zur Verfügung gestellt.

Since this package uses both the SOAP web service and GET requests, I assume that this discontinuation will render the package dysfunctional. 

Do you have this on your radar already and do you plan to adjust your package accordingly?

This would be highly appreciated! Keep up the good work! 

Best wishes 
Thomas

**Comment by sumtxt** [comment]
Thanks. I suspect that I won't update wiesbaden further as much of it's functionality is now available through: https://correlaid.github.io/restatis/index.html
