### ISSUE TITLE
landesdatenbank.nrw.de - NullPointerExceptions

### ISSUE THREAD

**Issue by daenemarque** [sumtxt/wiesbaden#6]
**R Code**
```
genesis <- c(user="username", password="correctpw", db="nrw")
d <- retrieve_datalist(tableseries="*", genesis=genesis)
```

**Result**
```
View(d)
"soapenv:Server.userExceptionjava.lang.NullPointerExceptionsb2-itd-278.admin.sb2"

```
I tried retrieving a table directly:
```
data <- retrieve_data(tablename="12612-01i", genesis=genesis)
metadata <- retrieve_metadata(tablename="12612-01i", genesis=genesis)
```
The object "data" just contains "No results found."; metadata just returns an empty dataframe.

**Question**
I double checked my user credentials. I am able to logon into the web-interface. Do you have an idea what might be the problem?
Thanks!

**Comment by sumtxt** [comment]
I just checked and I get the same error with correct credentials. It might be something with their server. I will check back tomorrow to see if the issue persists.

**Comment by sumtxt** [comment]
Their service is down. I sent them an email.

**Comment by sumtxt** [comment]
They are looking into it. Seems to be a bigger issue.

**Comment by sumtxt** [comment]
They fixed it. Works now.
