### ISSUE TITLE
genesis kostenfrei

### ISSUE THREAD

**Issue by janwilimzig** [sumtxt/wiesbaden#7]
Erst einmal vielen Dank für die Erstellung des Packages. 

"This package can only be used after a registration on the respective website to obtain a personal login name and password. The registration is free for all databases except genesis.destatis.de."

genesis.destatis.de ist mittlerweile auch kostenfrei (https://www.destatis.de/DE/Presse/Pressemitteilungen/2019/01/PD19_006_p001.html). 

Ich habe mich kostenfrei bei destatis registriert. Dennoch kann ich mit wiesbaden nicht auf genesis zugreifen. Die Abfrage der Tabellen über XML via genesis-API funktioniert hingegen. Woran kann es liegen, dass ich mich über die API verbinden kann, mit dem Package aber nicht? 

Beste Grüße,
Jan

**Comment by sumtxt** [comment]
Die PM ist leider nicht ganz korrekt. Freigeschaltet wurden einige API services für die kostenfreie Benutzung aber nicht alle. tabelleDownload gehört denke ich dazu, d.h. download_csv() sollte funktionieren. Aber der Zugriff auf die data cubes via DatenExport (-> retrieve_data()) gehört leider  nicht dazu. Gerne mal eine Email an destatis schreiben und darüber beklagen. Vielleicht schalten sie dann irgendwann mal alles frei.
