### ISSUE TITLE
retrieve_data -- bildungsmonitoring - sachmerkmal & sachschluessel

### ISSUE THREAD

**Issue by daenemarque** [sumtxt/wiesbaden#9]
**Question**
I tried to use the sachmerkmal and sachschluessel parameters to retrieve only specific data in a certain table. How to apply sachmerkmal & sachschluessel correctly?

**R Code**
`data <- retrieve_data(tablename="05--A024A", startyear="2016", endyear="2016", genesis=genesis_bm, sachmerkmal="ERWAQ7", sachschluessel="ARBEITSLOS05")`
I hoped that this would result in a table that only includes rows related to "ARBEITSLOS05"

**Result**
`head(data)`
  id05--A NW-KRE       ERWAQ7 JAHR ERWP06_val ERWP06_qual ERWP06_lock ERWP06_err
1       D  05111 ARBEITSLOS05 2016      10077           e          NA          0
2       D  05111 ARBEITSLOS06 2016       1888           e          NA          0
3       D  05111 ARBEITSLOS08 2016       9199           e          NA          0
4       D  05111 ARBEITSLOS12 2016        271           e          NA          0
5       D  05111 ARBEITSLOS13 2016       1541           e          NA          0
6       D  05111 ARBEITSLOS14 2016       4793           e          NA          0

The retrieved data is identical to data retrieved without the sachmerkmal and sachschluessel parameters (`data <- retrieve_data(tablename="05--A024A", startyear="2016", endyear="2016", genesis=genesis_bm)`) and includes also values for ARBEITSLOS06,...08,... etc.

The issue is not related to this specific combination of sachmerkmal and sachschluessel. I tried a different table which uses the sachmerkmal "GES" (like the example on page 29 of the genesis documentation: https://www-genesis.destatis.de/genesis/misc/GENESIS-Webservices_Einfuehrung.pdf) and was not successful either:
`data <- retrieve_data(tablename="05--D091", genesis=genesis_bm, sachmerkmal="GES", sachschluessel="GESM")`
The table refers to the number of teachers, I hoped I could only retrieve the number of male teachers (code GESM).

Thank you for taking your time!

**Comment by sumtxt** [comment]
I fixed it. The previous version ignored these parameters (sachmerkmal/sachschluessel). After you update your package via install_github("sumtxt/wiesbaden") it should work.
